name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout source code (pullจาก Repo ลงมาใน workspace)
      - name: Check out code
        uses: actions/checkout@v2

      # 2) ติดตั้ง Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # 3) Deploy ขึ้น Firebase Hosting
      - name: Deploy to Firebase Hosting
        run: firebase deploy --only "hosting:sawasdee-legal" --project sawasdee-legal
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
